stages:
- name: deploy yaml
  steps:
  - applyYamlConfig:
      path: ./IoT-Agent-Deployment.yml
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - applyYamlConfig:
      path: ./IoT-Agent-service.yml
    when:
      branch:
        include:
        - master
      event:
        include:
        - push
        - pull_request
  - applyYamlConfig:
      path: ./Ingress.yml.txt
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        apt-get update
        apt-get install sshpass
        sshpass -p test ssh -tt -o StrictHostKeyChecking=no test@192.168.100.117 ./unit_test_iot.sh
timeout: 60
notification: {}
