stages:
- name: deploy yaml
  steps:
  - applyYamlConfig:
      path: ./IoT-Agent-Deployment.yml
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - applyYamlConfig:
      path: ./IoT-Agent-service.yml
    when:
      branch:
        include:
        - master
      event:
        include:
        - push
        - pull_request
  - applyYamlConfig:
      path: ./Ingress.yml.txt
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - runScriptConfig:
      image: python:latest
      shellScript: "apt-get update\napt-get install sshpass\nsshpass -p test ssh -tt
        -o StrictHostKeyChecking=no test@192.168.100.117 "
timeout: 60
notification: {}
